services:
  - type: web
    name: zloy-misha-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
    plan: free
    region: oregon
    maxShutdownDelaySeconds: 10
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    autoDeploy: true
    branch: main
